[package]
name = "lakeside"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8.1"
heron = { version = "4.0.0", features = ["2d"] }
bevy-inspector-egui = "0.12"
